apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nvidia-network-operator
resources:
  - configmap-nic-policy-scripts.yaml
  - job-configure-nic-policy.yaml
  - nicconfigurationtemplate-roce.yaml
