apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sriovnetworknodepolicy-port1.yaml
  - sriovnetworknodepolicy-port2.yaml
  - sriovnetwork-port1.yaml
  - sriovnetwork-port2.yaml
