apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      kind: LLMInferenceService
      name: pd-performance
    patch: |
      apiVersion: serving.kserve.io/v1alpha2
      kind: LLMInferenceService
      metadata:
        name: pd-performance
      spec:
        template:
          imagePullSecrets:
            - name: rhai-pull-secret
        prefill:
          template:
            imagePullSecrets:
              - name: rhai-pull-secret
