apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-llm

resources:
  - ../base

patches:
  - target:
      kind: InferenceService
      name: vllm
    patch: |-
      - op: replace
        path: /metadata/name
        value: phi-vllm
      - op: replace
        path: /spec/predictor/model/storageUri
        value: "hf://microsoft/Phi-3.5-mini-instruct"
  - target:
      kind: Service
      name: vllm-lb
    patch: |-
      - op: replace
        path: /metadata/name
        value: phi-vllm-lb
      - op: replace
        path: /spec/selector/app
        value: isvc.phi-vllm-predictor
  - target:
      kind: PodMonitor
      name: vllm-monitor
    patch: |-
      - op: replace
        path: /metadata/name
        value: phi-vllm-monitor
      - op: replace
        path: /spec/selector/matchLabels/serving.kserve.io~1inferenceservice
        value: phi-vllm
