apiVersion: serving.kserve.io/v1alpha2
kind: LLMInferenceService
metadata:
  name: pd-performance
spec:
  model:
    name: openai/gpt-oss-120b
    uri: hf://openai/gpt-oss-120b
    replicas: 2
    template:
      imagePullSecrets:
        - name: rhai-pull-secret
      containers:
        - name: main
          env:
            - name: VLLM_NIXL_SIDE_CHANNEL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: VLLM_ADDITIONAL_ARGS
              value: --tensor-parallel-size 4 --max-model-len 40960 --block-size 128 --no-disable-hybrid-kv-cache-manager --kv-transfer-config '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
          ports:
            - containerPort: 5600
              name: nixl
              protocol: TCP
          resources:
            limits:
              cpu: '16'
              memory: 64Gi
              nvidia.com/gpu: '4'
              rdma/ib: '1'
            requests:
              cpu: '16'
              memory: 16Gi
              nvidia.com/gpu: '4'
              rdma/ib: '1'
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
            - name: kserve-provision-location
              mountPath: /mnt/models
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
        - name: kserve-provision-location
          persistentVolumeClaim:
            claimName: model-cache-pvc
  prefill:
    replicas: 4
    template:
      imagePullSecrets:
        - name: rhai-pull-secret
      containers:
        - name: main
          env:
            - name: VLLM_NIXL_SIDE_CHANNEL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: VLLM_ADDITIONAL_ARGS
              value: --tensor-parallel-size 2 --max-model-len 40960 --gpu-memory-utilization 0.88 --block-size 128 --no-disable-hybrid-kv-cache-manager --kv-transfer-config '{"kv_connector":"NixlConnector","kv_role":"kv_both"}'
          ports:
            - containerPort: 5600
              name: nixl
              protocol: TCP
          resources:
            limits:
              cpu: '16'
              memory: 64Gi
              nvidia.com/gpu: '2'
              rdma/ib: '1'
            requests:
              cpu: '16'
              memory: 16Gi
              nvidia.com/gpu: '2'
              rdma/ib: '1'
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
            - name: kserve-provision-location
              mountPath: /mnt/models
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
        - name: kserve-provision-location
          persistentVolumeClaim:
            claimName: model-cache-pvc
  router:
    gateway: {}
    route: {}
  scheduler:
    template:
      containers:
        - name: main
          args:
            - -v=10
          resources: {}
        - name: tokenizer
          resources: {}
