apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - machineconfig-iommu-pt.yaml
  - ../../common/03-worker-gpu-rdma-config

patches:
  - target:
      kind: MachineConfig
      name: 99-gpu-worker-crio-memlock
    patch: |
      - op: replace
        path: /metadata/name
        value: 99-b200-gpu-crio-memlock
      - op: replace
        path: /metadata/labels/machineconfiguration.openshift.io~1role
        value: b200-gpu
